apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: avatar
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - server-deployment.yaml
  - server-service.yaml
  - ingress.yaml
  - worker-deployment.yaml
  - worker-service.yaml
  - rbac.yaml
  - hpa.yaml
  - networkpolicy.yaml
  - deps/postgres.yaml
  - deps/minio.yaml
  - deps/rabbitmq.yaml
