apiVersion: v1
kind: ServiceAccount
metadata:
  name: avatar-service
  namespace: avatar
  labels:
    app: avatar-service
    app.kubernetes.io/part-of: gophprofile
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: avatar-worker
  namespace: avatar
  labels:
    app: avatar-worker
    app.kubernetes.io/part-of: gophprofile
automountServiceAccountToken: false
