apiVersion: v1
kind: Secret
metadata:
  name: avatar-secrets
  namespace: avatar
  labels:
    app.kubernetes.io/part-of: gophprofile
type: Opaque
stringData:
  database-dsn: "postgres://USER:PASSWORD@postgres:5432/avatar?sslmode=disable"
  s3-access-key: "CHANGE_ME"
  s3-secret-key: "CHANGE_ME"
  rabbitmq-url: "amqp://USER:PASSWORD@rabbitmq:5672/"
