apiVersion: v1
kind: Secret
metadata:
  name: avatar-secrets
  namespace: avatar
  labels:
    app: avatar-service
    app.kubernetes.io/part-of: gophprofile
type: Opaque
stringData:
  database-dsn: "postgres://avatar:avatar@postgres:5432/avatar?sslmode=disable"
  s3-access-key: "minioadmin"
  s3-secret-key: "minioadmin"
  rabbitmq-url: "amqp://guest:guest@rabbitmq:5672/"
