dependencies:
  enabled: true

ingress:
  className: traefik

autoscaling:
  enabled: true

serviceMonitor:
  enabled: false

networkPolicy:
  ingressNamespaces:
    - kube-system

migrate:
  hook: post-install,pre-upgrade

config:
  baseURL: http://avatars.example.com
  s3Endpoint: minio:9000
  otelEnvironment: local
  otelTracingEnabled: "false"
  otelLogsEnabled: "false"

secret:
  create: true
  databaseDsn: postgres://USER:PASSWORD@postgres:5432/avatar?sslmode=disable
  s3AccessKey: CHANGE_ME
  s3SecretKey: CHANGE_ME
  rabbitmqUrl: amqp://USER:PASSWORD@rabbitmq:5672/
