{{- if and .Values.secret.create (not .Values.secret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gophprofile.secretName" . }}
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
    {{- include "gophprofile.serverSelectorLabels" . | nindent 4 }}
type: Opaque
stringData:
  database-dsn: {{ .Values.secret.databaseDsn | quote }}
  s3-access-key: {{ .Values.secret.s3AccessKey | quote }}
  s3-secret-key: {{ .Values.secret.s3SecretKey | quote }}
  rabbitmq-url: {{ .Values.secret.rabbitmqUrl | quote }}
{{- end }}
