{{- if .Values.worker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gophprofile.workerName" . }}-metrics
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
    {{- include "gophprofile.workerSelectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    {{- include "gophprofile.workerSelectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.ports.metrics }}
      targetPort: metrics
{{- end }}
